## Hospital Data
Here we assume that we are dealing with private data from the hospitals.
Suppose we have 10 hospitals who trained our model for their private data and we want to use their model to predict our unlabeled data
### E.g
We have 10,000 unlabeled images that we need to classify using these 10 hospital models and use the outcome to be what we shall use for our model retrainer


In [9]:
# imports
import numpy as np

In [10]:
# Define the data parameters
num_trainers = 10             # The number of Hospitls that are training/running out models
num_examples = 10000          # The Number of unlabled images we have at hand that we want to predict using the trained models from the hospitals
num_classes = 10              # Number of labels in the model (our classifier)

In [11]:
# Generate a random prediction (Fakes) of the models for our 10000 samples
predictions = (np.random.rand(num_trainers, num_examples)*num_classes).astype(int)
predictions

array([[4, 5, 3, ..., 8, 4, 6],
       [1, 9, 3, ..., 5, 0, 4],
       [3, 8, 6, ..., 1, 6, 6],
       ...,
       [7, 6, 1, ..., 5, 4, 7],
       [4, 7, 3, ..., 0, 5, 7],
       [3, 0, 4, ..., 2, 8, 6]])

In [12]:
# Prediction shape
predictions.shape

(10, 10000)

In [13]:
# For the first image, the 10 prredictions from the 10 hospitals is
image_label = predictions[:, 0]
image_label

array([4, 1, 3, 5, 9, 5, 9, 7, 4, 3])

In [14]:
# Count the number of labels so as to get the reliable prediction
pred_label_count = np.bincount(image_label, minlength=num_classes)
pred_label_count

array([0, 1, 0, 2, 2, 2, 0, 1, 0, 2], dtype=int64)

In [15]:
predicted_label = np.argmax(pred_label_count)
predicted_label

3

In [16]:
# Hyper parameters for noise 
epsilon = 0.1
sensitivity = 1
beta = sensitivity/epsilon
beta

10.0

In [17]:
for i in range(len(pred_label_count)):
    pred_label_count[i] += np.random.laplace(0, beta, 1)
    
new_labels = pred_label_count
new_labels

array([  5,   7,  30,   0, -12,  24,  -8,  16, -27,  -5], dtype=int64)

In [ ]:
new_predictions = []
for img_data in predictions.transpose():
    
    pred_label_count = np.bincount(img_data, minlength=num_classes)
    
    pred_level_count_before = np.bincount(img_data, minlength=num_classes)
    pred_before = np.argmax(pred_level_count_before)
    
    epsilon = 0.1
    sensitivity = 1
    beta = sensitivity/epsilon
    
    for i in range(len(pred_label_count)):
        pred_label_count[i] += np.random.laplace(0, beta, 1)
    
    pred =np.argmax(pred_label_count)
    print(img_data, '->', pred_level_count_before,'->', pred_label_count, '--->',pred_before, '->', pred)
    
    #for i in range(len)

[4 1 3 5 9 5 9 7 4 3] -> [0 1 0 2 2 2 0 1 0 2] -> [29  1 -5  8  3 -1 -3  2 -6  5] ---> 3 -> 0
[5 9 8 6 2 1 0 6 7 0] -> [2 1 1 0 0 1 2 1 1 1] -> [  8 -14 -25  15   1   0 -18  -8  -9   0] ---> 0 -> 3
[3 3 6 8 6 2 1 1 3 4] -> [0 2 1 3 1 0 2 0 1 0] -> [ -7  31   5  -5   4 -24  -1 -46   0  -1] ---> 3 -> 1
[5 3 7 6 7 5 6 5 2 9] -> [0 0 1 1 0 3 2 2 0 1] -> [ 30  -6  -8  22  -4   6 -14 -11  11  16] ---> 5 -> 0
[9 6 9 0 4 4 0 8 1 2] -> [2 1 1 0 2 0 1 0 1 2] -> [-24  13  21  21  -2  11   3  -6 -27   2] ---> 0 -> 2
[1 6 6 2 6 0 5 2 4 6] -> [1 1 2 0 1 1 4 0 0 0] -> [ 18  -2  35  23   0  -9   8 -28 -11 -24] ---> 6 -> 2
[4 1 1 8 7 7 4 6 3 6] -> [0 2 0 1 2 0 2 2 1 0] -> [ -2   0   5   3   9  17   5   2  -1 -12] ---> 1 -> 5
[0 1 6 7 1 1 2 5 2 9] -> [1 3 2 0 0 1 1 1 0 1] -> [ -8   1   3  -1  -5   8 -11   0   0   3] ---> 1 -> 5
[6 8 6 3 0 7 6 3 2 7] -> [1 0 1 2 0 0 3 2 1 0] -> [  1  -5  -8  -5   3   4 -14  12  -1  13] ---> 6 -> 9
[1 8 0 1 0 4 6 5 6 2] -> [2 2 1 0 1 1 2 0 1 0] -> [  7   8 -27 -16   8  26