## Generate a sample database
Create a sample database that takes a number of records, randomly assigns a given attribute of concern and removes a record from each of the parallel databases generated from the original.
With this parallel databases, we can then perform similarity checks

In [16]:
# Import modules
import torch

In [17]:
# Create a parallel db generator which removes one record from the original db and keeps the rest of the records
def par_db_generator(db, idx):
    return torch.cat((db[0:idx], db[idx+1:]))

In [18]:
# Backle up the parallel databases together
# it depends entirely on the length of the first db
def par_dbs(db):
    """This creates an array with the datase columns = len(db-1)
    Since we are removing one record at a time and returning the remaining values
    """
    db_all = []
    
    for i in range(len(db)):
        par_db = par_db_generator(db, i)
        db_all.append(par_db)
        
    return db_all

In [19]:
# Create a function to generate the required data based on a given sample of users or records
def generate_db(rec_no):
    """This function generates the db that is then usd to generate the parallel dbs"""
    db = torch.rand(rec_no)>0.5
    print('Original DB\n{}'.format(db))
    
    #Generate the entire parallel db
    pdb = par_dbs(db)
    
    return pdb    

In [20]:
db = generate_db(10)
db

Original DB
tensor([1, 0, 0, 0, 0, 1, 0, 1, 1, 0], dtype=torch.uint8)


[tensor([0, 0, 0, 0, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 0, 1, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 0, 1, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 0, 1, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 0, 1, 0, 1, 1], dtype=torch.uint8)]